let mindPoints=0;let completedActivities=0;let currentProfile={};

function showScreen(screenId){document.querySelectorAll(".screen").forEach(screen=>screen.classList.remove("active"));document.getElementById(screenId).classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
function toggleImproveOptions(){document.getElementById("improveOptions").classList.toggle("hidden")}
function getCheckedValues(){return Array.from(document.querySelectorAll('.multi input[type="checkbox"]:checked')).map(item=>item.value)}
function updateImproveButton(){const improvements=getCheckedValues();const button=document.querySelector(".dropdown-toggle");if(improvements.length===0){button.textContent="Select improvement areas"}else if(improvements.length<=2){button.textContent=improvements.join(", ")}else{button.textContent=improvements.length+" areas selected"}}

function determinePrimaryPath(improvements,challenge){const all=[...improvements,challenge].join(" ").toLowerCase();if(all.includes("panic")||all.includes("anxiety")||all.includes("racing thoughts"))return{name:"Calm & Anxiety",title:"Calm Foundations",daily:["60-second breathing reset","Grounding exercise","Name one thing you can control today"]};if(all.includes("overthinking")||all.includes("negative"))return{name:"Overthinking",title:"Mental Clarity",daily:["Thought challenge","Worry release journal","One-minute mindful pause"]};if(all.includes("confidence")||all.includes("social anxiety")||all.includes("low confidence")||all.includes("performance"))return{name:"Confidence",title:"Confidence Builder",daily:["Small courage challenge","Confidence script","Post-action reflection"]};if(all.includes("focus"))return{name:"Focus",title:"Focus Reset",daily:["Distraction clear-out","5-minute focus timer","One-task commitment"]};if(all.includes("stress")||all.includes("burnout")||all.includes("work stress"))return{name:"Stress & Burnout",title:"Stress Recovery",daily:["Body tension scan","Recovery break","One boundary for today"]};if(all.includes("motivation"))return{name:"Motivation",title:"Momentum Builder",daily:["Tiny goal","Win log","One next step"]};return{name:"Balanced Growth",title:"Steady Foundations",daily:["Breathing reset","Short reflection","One steady action"]}}

function determineMindType(improvements,challenge,hope){const all=[...improvements,challenge,hope].join(" ").toLowerCase();if(all.includes("racing thoughts")||all.includes("panic")||all.includes("stress"))return{name:"🌊 Storm Navigator",description:"You may feel pulled by pressure, racing thoughts, or emotional storms, but your goal is to become steadier under stress."};if(all.includes("overthinking")||all.includes("negative"))return{name:"🧠 Deep Thinker",description:"Your mind works hard to understand and prepare, but SteadyMind will help you turn mental noise into clarity."};if(all.includes("confidence")||all.includes("social anxiety"))return{name:"🦁 Quiet Leader",description:"You may doubt yourself at times, but there is courage there. SteadyMind will help you build it through small actions."};if(all.includes("burnout")||all.includes("work stress"))return{name:"🔥 Burned-Out Achiever",description:"You keep pushing, but your mind and body need recovery. SteadyMind will help you rebuild energy and balance."};if(all.includes("motivation")||all.includes("energized"))return{name:"🚀 Momentum Builder",description:"You want to move forward. SteadyMind will help you turn small wins into steady progress."};return{name:"🌱 Steady Builder",description:"You are ready to grow with calm, consistency, and simple daily steps."}}

function getLevelName(points){if(points>=400)return"Level 5: SteadyMind Master";if(points>=300)return"Level 4: Resilient Thinker";if(points>=200)return"Level 3: Storm Navigator";if(points>=100)return"Level 2: Steady Builder";return"Level 1: Calm Seeker"}
function updateXP(){const capped=Math.min(mindPoints,100);document.getElementById("xpFill").style.width=capped+"%";document.getElementById("xpText").textContent=`${mindPoints} / 100 Mind Points`;document.getElementById("levelName").textContent=getLevelName(mindPoints);document.getElementById("activitiesText").textContent=completedActivities;document.getElementById("streakText").textContent=completedActivities>0?"1 day":"0 days"}
function completeActivity(){mindPoints+=5;completedActivities+=1;updateXP()}

function buildPlan(){const improvements=getCheckedValues();const challenge=document.getElementById("challenge").value;const time=document.getElementById("timeCommitment").value;const hope=document.getElementById("hope").value;const userType=document.getElementById("userType").value;const improvementText=improvements.length?improvements.join(", "):"your steady mind";const path=determinePrimaryPath(improvements,challenge);const mindType=determineMindType(improvements,challenge,hope);const supportingPaths=improvements.filter(item=>item!==path.name).slice(0,3);currentProfile={improvements,challenge,time,hope,userType,path,mindType};document.getElementById("profileCard").innerHTML=`<strong>Your profile:</strong><br>• User type: ${userType}<br>• Wants to improve: ${improvementText}<br>• Biggest challenge: ${challenge}<br>• Desired feeling: ${hope}<br>• Time available: ${time} per day`;document.getElementById("mindTypeCard").innerHTML=`<strong>${mindType.name}</strong><p>${mindType.description}</p>`;document.getElementById("pathCard").innerHTML=`<strong>Primary Path: ${path.title}</strong><br>Supporting Focus: ${supportingPaths.length?supportingPaths.join(", "):"Steady daily habits"}<br><br>This path is designed to help you feel more <strong>${hope}</strong> while working through <strong>${challenge}</strong>.`;document.getElementById("dailyPlanCard").innerHTML=`<strong>Today's Focus: ${path.name}</strong><br>Today's Goal: Take one small action that helps you steady your mind.<br><br><strong>Your ${time} routine:</strong><ol><li>${path.daily[0]}</li><li>${path.daily[1]}</li><li>${path.daily[2]}</li></ol><strong>Progress:</strong> Day 1 of 30`;document.getElementById("weeklyCard").innerHTML=`<strong>This week, SteadyMind will track:</strong><br>• Anxiety and stress trends<br>• Confidence and focus growth<br>• Activities completed<br>• Mind Points earned<br><br>Your first goal: complete one steady activity today.`;updateXP();showScreen("dashboard")}

function saveCheckIn(){const mood=document.getElementById("mood").value;const need=document.getElementById("need").value;document.getElementById("checkinResult").classList.remove("hidden");document.getElementById("checkinResult").innerHTML=`<strong>Check-in saved.</strong><br>Your mind feels <strong>${mood}</strong>. Today, focus on <strong>${need}</strong>.`;completeActivity()}
function startBreathing(){const box=document.getElementById("breathingBox");const steps=["Breathe in slowly...","Hold gently...","Breathe out fully...","Rest. You are safe in this moment."];let i=0;box.textContent=steps[i];const timer=setInterval(()=>{i++;if(i>=steps.length){clearInterval(timer);box.textContent="Reset complete. You earned +5 XP.";completeActivity()}else{box.textContent=steps[i]}},3000)}
function playGame(game){document.getElementById("gameResult").classList.remove("hidden");document.getElementById("gameResult").innerHTML=`<strong>${game}</strong><br>Prototype activity complete. In the full app, this will become an interactive exercise. +5 XP`;completeActivity()}
function openLesson(topic){const lessons={"Anxiety Basics":"Anxiety is your body's alarm system. The goal is not to fear the alarm, but to understand it and respond steadily.","Overthinking":"Overthinking is often your mind trying to solve uncertainty. SteadyMind helps you separate useful planning from mental noise.","Confidence":"Confidence grows after action. Small repeated courage steps build self-trust.","Sleep":"Sleep improves when your body feels safe. Wind-down routines teach your nervous system to settle."};document.getElementById("lessonResult").classList.remove("hidden");document.getElementById("lessonResult").innerHTML=`<strong>${topic}</strong><br>${lessons[topic]}`;}
function saveJournal(){const text=document.getElementById("journalText").value.trim();document.getElementById("journalResult").classList.remove("hidden");document.getElementById("journalResult").innerHTML=text?`<strong>Journal saved.</strong><br>You gave your thoughts a place to land. +5 XP`:"Write one sentence before saving.";if(text)completeActivity()}